server:
  port: 9999

spring:
  data:
    mongodb:
      host: mongodb://localhost:27017
      database: auth-demo

jwt:
  secret:
    key: 1234asdfqwersdafasdfsadfagefgegbrevqebverbregrqegfrevervrqewerverqeqrvreadvwedvaerfv123351